version: '3.8'
services:
  app:
    build:
      context: .
    working_dir: /var/www/battle-of-stalingrad
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/battle-of-stalingrad
      - mysql-data:/var/lib/mysql
  couchbase:
    image: couchbase:community-7.2.4
    environment:
      - CLUSTER_NAME=battleofstalingrad
      - COUCHBASE_ADMINISTRATOR_USERNAME=development
      - COUCHBASE_ADMINISTRATOR_PASSWORD=secret
      - COUCHBASE_BUCKET=battleofstalingrad
      - COUCHBASE_PORT=8091
      - COUCHBASE_USERNAME=development
      - COUCHBASE_PASSWORD=secret
      - COUCHBASE_BUCKET_RAMSIZE=256
      - COUCHBASE_BUCKET_TYPE=couchbase
      - COUCHBASE_BUCKET_PRIORITY=high
      - COUCHBASE_BUCKET_EVICTION_POLICY=valueOnly
      - COUCHBASE_CLUSTER_NAME=battleofstalingrad
      - COUCHBASE_CLUSTER_RAMSIZE=1024
      - COUCHBASE_CLUSTER_INDEX_RAMSIZE=512
      - COUCHBASE_CLUSTER_EVENTING_RAMSIZE=256
      - COUCHBASE_CLUSTER_FTS_RAMSIZE=256
      - COUCHBASE_CLUSTER_ANALYTICS_RAMSIZE=1024
      - COUCHBASE_CLUSTER_QUERY_RAMSIZE=512
      - COUCHBASE_CLUSTER_INDEX_STORAGE_SETTING=default
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
volumes:
  mysql-data:
